import {
  Container,
  Heading,
} from "@chakra-ui/react";
import { useEffect, useState } from "react";
import OMAForm from "./components/OMAForm";

function App() {
  const [fields, setFields] = useState([])

  useEffect(() => {
    fetch('/fields.json')
      .then(response => response.json())
      .then(data => setFields(data))
  }, [])

  return (
    <Container>
      <Heading as="h1" size="lg" noOfLines={1}>
        A form generated by config object
      </Heading>
      <OMAForm fields={fields} method="POST" />
    </Container>
  );
}

export default App;
