name: Checks
on:
  pull_request:
    branches:
      - main
    types:
      - opened 
      - edited
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Component Test
        run: npm run test
